CREATE DATABASE CLC18_QLDA2020_18127070
GO
USE CLC18_QLDA2020_18127070

GO
CREATE TABLE NHANVIEN
(
	HoNV NVARCHAR(15),
	TenLot NVARCHAR(15),
	TenNV NVARCHAR(15),
	MaNV CHAR(9),
	NgSinh DATE,
	DChi NVARCHAR(30),
	Phai NVARCHAR(3) CHECK (PHAI IN ('Nam', N'Nữ')), 
	Luong FLOAT,
	Ma_NQL CHAR(9),
	PHG INT,
	CONSTRAINT PK_NHANVIEN
	PRIMARY KEY (MaNV)
)

GO
CREATE TABLE PHONGBAN
(
	TenPHG NVARCHAR(15),
	MaPHG INT, 
	TrPHG CHAR(9),
	Ng_NhanChuc DATE,
	CONSTRAINT PK_PHONGBAN
	PRIMARY KEY (MaPHG)
)

GO
CREATE TABLE DIADIEM_PHG
(
	MaPHG INT,
	DiaDiem NVARCHAR(15),
	CONSTRAINT PK_DIADIEM_PHG
	PRIMARY KEY (MaPHG, DiaDiem)
)

GO
CREATE TABLE CONGVIEC
(
	MaDA INT,
	STT INT,
	Ten_Cong_Viec NVARCHAR(50),
	CONSTRAINT PK_CONGVIEC
	PRIMARY KEY (MaDA, STT)
)

GO
CREATE TABLE PHANCONG
(
	Ma_NVien CHAR(9),
	MaDA INT,
	STT INT,
	ThoiGian DECIMAL(5, 1),
	CONSTRAINT PK_PHANCONG
	PRIMARY KEY (Ma_NVien, MaDA, STT)
)

GO
CREATE TABLE THANNHAN
(
	Ma_NVien CHAR(9),
	TenTN NVARCHAR(15),
	Phai NVARCHAR(3) CHECK (PHAI IN ('Nam', N'Nữ')), 
	NgSinh DATE,
	QuanHe NVARCHAR(15),
	CONSTRAINT PK_THANNHAN
	PRIMARY KEY (Ma_NVien, TenTN)
)

GO
CREATE TABLE DEAN
(
	TenDA NVARCHAR(15),
	MaDA INT,
	Ddiem_DA NVARCHAR(15),
	Phong INT,
	CONSTRAINT PK_DEAN
	PRIMARY KEY (MaDA)
)

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_PHONGBAN
FOREIGN KEY (PHG)
REFERENCES PHONGBAN(MaPHG)

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_NHANVIEN
FOREIGN KEY (Ma_NQL)
REFERENCES NHANVIEN(MaNV)

ALTER TABLE PHONGBAN
ADD CONSTRAINT FK_PHONGBAN_NHANVIEN
FOREIGN KEY (TrPHG)
REFERENCES NHANVIEN(MaNV)

ALTER TABLE DIADIEM_PHG
ADD CONSTRAINT FK_DIADIEM_PHG_PHONGBAN
FOREIGN KEY (MaPHG)
REFERENCES PHONGBAN(MaPHG)

ALTER TABLE PHANCONG
ADD CONSTRAINT FK_PHANCONG_CONGVIEC
FOREIGN KEY (MaDA, STT)
REFERENCES CONGVIEC(MaDA, STT)

ALTER TABLE PHANCONG
ADD CONSTRAINT FK_PHANCONG_NHANVIEN
FOREIGN KEY (Ma_NVien)
REFERENCES NHANVIEN(MaNV)

ALTER TABLE CONGVIEC 
ADD CONSTRAINT FK_CONGVIEC_DEAN
FOREIGN KEY (MaDA)
REFERENCES DEAN(MaDA)

ALTER TABLE THANNHAN
ADD CONSTRAINT FK_THANNHAN_NHANVIEN
FOREIGN KEY (Ma_NVien)
REFERENCES NHANVIEN(MaNV)

ALTER TABLE DEAN
ADD CONSTRAINT FK_DEAN_PHONGBAN
FOREIGN KEY (Phong)
REFERENCES PHONGBAN(MaPHG)

INSERT INTO PHONGBAN(TenPHG, MaPHG, TrPHG, Ng_NhanChuc) 
	VALUES (N'Nghiên cứu', 5, NULL, '05/22/1978')
INSERT INTO PHONGBAN(TenPHG, MaPHG, TrPHG, Ng_NhanChuc) 
	VALUES (N'Điều hành', 4, NULL, '01/01/1985')
INSERT INTO PHONGBAN(TenPHG, MaPHG, TrPHG, Ng_NhanChuc) 
	VALUES (N'Quản lý', 1, NULL, '06/19/1971')

INSERT INTO NHANVIEN(HoNV, TenLot, TenNV, MaNV, NgSinh, DChi, Phai, Luong, Ma_NQL, PHG)
	VALUES (N'Đinh', N'Bá', N'Tiến', '009', '02/11/1960', N'119 Cống Quỳnh, Tp HCM', 'Nam', 30000, NULL, 5)
INSERT INTO NHANVIEN(HoNV, TenLot, TenNV, MaNV, NgSinh, DChi, Phai, Luong, Ma_NQL, PHG)
	VALUES (N'Nguyễn', N'Thanh', N'Tùng', '005', '08/20/1962', N'222 Nguyễn Văn Cừ, Tp HCM', 'Nam', 40000, NULL, 5)
INSERT INTO NHANVIEN(HoNV, TenLot, TenNV, MaNV, NgSinh, DChi, Phai, Luong, Ma_NQL, PHG)
	VALUES (N'Bùi', N'Ngọc', N'Hằng', '007', '03/11/1954', N'332 Nguyễn Thái Học, Tp HCM', 'Nam', 25000, NULL, 4)
INSERT INTO NHANVIEN(HoNV, TenLot, TenNV, MaNV, NgSinh, DChi, Phai, Luong, Ma_NQL, PHG)
	VALUES (N'Lê', N'Quỳnh', N'Như', '001', '02/01/1967', N'221 Hồ Văn Huê, Tp HCM', N'Nữ', 43000, NULL, 4)
INSERT INTO NHANVIEN(HoNV, TenLot, TenNV, MaNV, NgSinh, DChi, Phai, Luong, Ma_NQL, PHG)
	VALUES (N'Nguyễn', N'Mạnh', N'Hùng', '004', '03/04/1967', N'95 Bà Rịa, Vũng Tàu', 'Nam', 38000, NULL, 5)
INSERT INTO NHANVIEN(HoNV, TenLot, TenNV, MaNV, NgSinh, DChi, Phai, Luong, Ma_NQL, PHG)
	VALUES (N'Trần', N'Thanh', N'Tâm', '003', '05/04/1957', N'34 Mai Thị Lư, Tp HCM', 'Nam', 25000, NULL, 5)
INSERT INTO NHANVIEN(HoNV, TenLot, TenNV, MaNV, NgSinh, DChi, Phai, Luong, Ma_NQL, PHG)
	VALUES (N'Trần', N'Hồng', N'Quang', '008', '09/01/1967', N'80 Lê Hồng Phong, Tp HCM', 'Nam', 25000, NULL, 4)
INSERT INTO NHANVIEN(HoNV, TenLot, TenNV, MaNV, NgSinh, DChi, Phai, Luong, Ma_NQL, PHG)
	VALUES (N'Phạm', N'Văn', N'Vinh', '006', '01/01/1965', N'45 Trưng Vương, Hà Nội', N'Nữ', 55000, NULL, 1)

UPDATE PHONGBAN SET TrPHG = '005' WHERE MaPHG = 5
UPDATE PHONGBAN SET TrPHG = '008' WHERE MaPHG = 4
UPDATE PHONGBAN SET TrPHG = '006' WHERE MaPHG = 1

UPDATE NHANVIEN SET Ma_NQL = '005' WHERE MaNV = '009' OR MaNV = '004' OR MaNV = '003'
UPDATE NHANVIEN SET Ma_NQL = '006' WHERE MaNV = '005' OR MaNV = '001'
UPDATE NHANVIEN SET Ma_NQL = '001' WHERE MaNV = '007' OR MaNV = '008'

INSERT INTO DIADIEM_PHG(MaPHG, DiaDiem) VALUES (1, 'TP HCM')
INSERT INTO DIADIEM_PHG(MaPHG, DiaDiem) VALUES (4, N'Hà Nội')
INSERT INTO DIADIEM_PHG(MaPHG, DiaDiem) VALUES (5, N'Vũng Tàu')
INSERT INTO DIADIEM_PHG(MaPHG, DiaDiem) VALUES (5, 'Nha Trang')
INSERT INTO DIADIEM_PHG(MaPHG, DiaDiem) VALUES (5, 'TP HCM')

INSERT INTO THANNHAN(Ma_NVien, TenTN, Phai, NgSinh, QuanHe)
	VALUES ('005', 'Trinh', N'Nữ', '04/05/1976', N'Con gái')
INSERT INTO THANNHAN(Ma_NVien, TenTN, Phai, NgSinh, QuanHe)
	VALUES ('005', 'Khang', 'Nam', '10/25/1973', 'Con trai')
INSERT INTO THANNHAN(Ma_NVien, TenTN, Phai, NgSinh, QuanHe)
	VALUES ('005', N'Phương', N'Nữ', '05/03/1948', N'Vợ chồng')
INSERT INTO THANNHAN(Ma_NVien, TenTN, Phai, NgSinh, QuanHe)
	VALUES ('001', 'Minh', 'Nam', '02/29/1932', N'Vợ chồng')
INSERT INTO THANNHAN(Ma_NVien, TenTN, Phai, NgSinh, QuanHe)
	VALUES ('009', N'Tiến', 'Nam', '01/01/1978', 'Con trai')
INSERT INTO THANNHAN(Ma_NVien, TenTN, Phai, NgSinh, QuanHe)
	VALUES ('009', N'Châu', N'Nữ', '12/30/1978', N'Con gái')
INSERT INTO THANNHAN(Ma_NVien, TenTN, Phai, NgSinh, QuanHe)
	VALUES ('009', N'Phương', N'Nữ', '05/05/1957', N'Vợ chồng')

INSERT INTO DEAN(TenDA, MaDA, Ddiem_DA, Phong) VALUES (N'Sản phẩm X', 1, N'Vũng Tàu', 5)
INSERT INTO DEAN(TenDA, MaDA, Ddiem_DA, Phong) VALUES (N'Sản phẩm Y', 2, 'Nha Trang', 5)
INSERT INTO DEAN(TenDA, MaDA, Ddiem_DA, Phong) VALUES (N'Sản phẩm Z', 3, 'TP HCM', 5)
INSERT INTO DEAN(TenDA, MaDA, Ddiem_DA, Phong) VALUES (N'Tin học hóa', 10, N'Hà Nội', 4)
INSERT INTO DEAN(TenDA, MaDA, Ddiem_DA, Phong) VALUES (N'Cáp quang', 20, N'TP HCM', 1)
INSERT INTO DEAN(TenDA, MaDA, Ddiem_DA, Phong) VALUES (N'Đào tạo', 30, N'Hà Nội', 4)

INSERT INTO CONGVIEC(MaDA, STT, Ten_Cong_Viec) VALUES (1, 1, N'Thiết kế sản phẩm X')
INSERT INTO CONGVIEC(MaDA, STT, Ten_Cong_Viec) VALUES (1, 2, N'Thử nghiệm sản phẩm X')
INSERT INTO CONGVIEC(MaDA, STT, Ten_Cong_Viec) VALUES (2, 1, N'Sản xuất sản phẩm Y')
INSERT INTO CONGVIEC(MaDA, STT, Ten_Cong_Viec) VALUES (2, 2, N'Quảng cáo sản phẩm Y')
INSERT INTO CONGVIEC(MaDA, STT, Ten_Cong_Viec) VALUES (3, 1, N'Khuyến mãi sản phẩm Z')
INSERT INTO CONGVIEC(MaDA, STT, Ten_Cong_Viec) VALUES (10, 1, N'Tin học hóa nhân sự tiền lương')
INSERT INTO CONGVIEC(MaDA, STT, Ten_Cong_Viec) VALUES (10, 2, N'Tin học hóa phòng kinh doanh')
INSERT INTO CONGVIEC(MaDA, STT, Ten_Cong_Viec) VALUES (20, 1, N'Lắp đặt cáp quang khu B')
INSERT INTO CONGVIEC(MaDA, STT, Ten_Cong_Viec) VALUES (30, 1, N'Đào tạo nhân viên Marketing')
INSERT INTO CONGVIEC(MaDA, STT, Ten_Cong_Viec) VALUES (30, 2, N'Đào tạo chuyên viên thiết kế')

INSERT INTO PHANCONG(Ma_NVien, MaDA, STT, ThoiGian) VALUES ('009', 1, 1, 32)
INSERT INTO PHANCONG(Ma_NVien, MaDA, STT, ThoiGian) VALUES ('009', 2, 2, 8)
INSERT INTO PHANCONG(Ma_NVien, MaDA, STT, ThoiGian) VALUES ('004', 3, 1, 40)
INSERT INTO PHANCONG(Ma_NVien, MaDA, STT, ThoiGian) VALUES ('003', 1, 2, 20.0)
INSERT INTO PHANCONG(Ma_NVien, MaDA, STT, ThoiGian) VALUES ('003', 2, 1, 20.0)
INSERT INTO PHANCONG(Ma_NVien, MaDA, STT, ThoiGian) VALUES ('008', 10, 1, 35)
INSERT INTO PHANCONG(Ma_NVien, MaDA, STT, ThoiGian) VALUES ('008', 30, 2, 5)
INSERT INTO PHANCONG(Ma_NVien, MaDA, STT, ThoiGian) VALUES ('001', 30, 1, 20)
INSERT INTO PHANCONG(Ma_NVien, MaDA, STT, ThoiGian) VALUES ('001', 20, 1, 15)
INSERT INTO PHANCONG(Ma_NVien, MaDA, STT, ThoiGian) VALUES ('006', 20, 1, 30)
INSERT INTO PHANCONG(Ma_NVien, MaDA, STT, ThoiGian) VALUES ('005', 3, 1, 10)
INSERT INTO PHANCONG(Ma_NVien, MaDA, STT, ThoiGian) VALUES ('005', 10, 2, 10)
INSERT INTO PHANCONG(Ma_NVien, MaDA, STT, ThoiGian) VALUES ('005', 20, 1, 10)
INSERT INTO PHANCONG(Ma_NVien, MaDA, STT, ThoiGian) VALUES ('007', 30, 2, 30)
INSERT INTO PHANCONG(Ma_NVien, MaDA, STT, ThoiGian) VALUES ('007', 10, 2, 10)

-- QUERY 1
-- 1
SELECT NV.TenNV FROM NHANVIEN NV  WHERE NV.PHG = 4
-- 2
SELECT NV.TenNV
FROM dbo.NHANVIEN NV WHERE NV.Luong > 30000
-- 3
SELECT NV.TenNV
FROM dbo.NHANVIEN NV WHERE NV.Luong > 25000 AND NV.PHG = 4
UNION
SELECT NV1.TenNV
FROM dbo.NHANVIEN NV1 WHERE NV1.Luong > 30000 AND NV1.PHG = 5
-- 4
SELECT NV.HoNV, NV.TenLot, NV.TenNV
FROM NHANVIEN NV
WHERE NV.DChi LIKE '%Tp HCM'
-- 5
SELECT NV.HoNV, NV.TenLot, NV.TenNV
FROM dbo.NHANVIEN NV WHERE SUBSTRING(NV.HoNV, 1, 1) LIKE 'N'
-- 6
SELECT PB.TenPHG, DD.DiaDiem
FROM dbo.PHONGBAN PB JOIN dbo.DIADIEM_PHG DD ON PB.MaPHG = DD.MaPHG
-- 7
SELECT NV.TenNV, PB.TenPHG AS TRUONGPHONGCUAPHONGBAN
FROM dbo.NHANVIEN NV JOIN dbo.PHONGBAN PB ON NV.MaNV = PB.TrPHG
-- 8
SELECT DA.TenDA, DA.MaDA, DA.Ddiem_DA, DA.Phong, PB.TenPHG, PB.MaPHG, PB.TrPHG, PB.Ng_NhanChuc
FROM dbo.DEAN DA, dbo.PHONGBAN PB
-- 9
SELECT NV.TenNV, NV.DChi
FROM dbo.NHANVIEN NV, dbo.PHONGBAN PB WHERE NV.PHG = PB.MaPHG AND PB.TenPHG = N'Nghiên cứu'
-- QUERY 2
-- 1
SELECT NV.NgSinh, NV.DChi
FROM dbo.NHANVIEN NV WHERE NV.TenNV = N'Tiến'
-- 2
SELECT NV.TenNV
FROM dbo.NHANVIEN NV WHERE YEAR(NV.NgSinh) < 1975
-- 3
SELECT NV.TenNV
FROM dbo.NHANVIEN NV WHERE NV.NgSinh < '04/30/1975'
-- 4
SELECT NV.TenNV FROM dbo.NHANVIEN NV WHERE NV.NgSinh < '04/30/1975'
UNION
SELECT NV.TenNV FROM NHANVIEN NV
WHERE NV.DChi LIKE '%Tp HCM'
UNION 
SELECT NV.TenNV FROM dbo.NHANVIEN NV WHERE NV.PHG = 4
-- 5
SELECT NV.TenNV, TN.TenTN
FROM dbo.NHANVIEN NV JOIN dbo.THANNHAN TN ON NV.MaNV = TN.Ma_NVien
WHERE NV.Phai = N'Nữ'
-- 6
SELECT DA.MaDA, DA.Phong, NV.HoNV, NV.TenLot, NV.TenNV, NV.DChi, NV.NgSinh
FROM DEAN DA INNER JOIN PHONGBAN PB ON DA.Phong = PB.MaPHG INNER JOIN dbo.NHANVIEN NV ON PB.TrPHG = NV.MaNV
WHERE DA.Ddiem_DA = N'Hà Nội'
-- 7
SELECT *
FROM dbo.NHANVIEN A LEFT JOIN dbo.NHANVIEN B ON A.MaNV = B.Ma_NQL
-- 8
SELECT NV.HoNV, NV.TenLot, NV.TenNV, TRP.HoNV AS HOTRUONGPHONG, TRP.TenLot AS TENLOTTRUONGPHONG, TRP.TenNV AS TENTRUONGPHONG
FROM dbo.NHANVIEN NV, dbo.NHANVIEN TRP, dbo.PHONGBAN PB
WHERE NV.PHG = PB.MaPHG AND PB.TrPHG = TRP.MaNV
-- 9
SELECT NV1.HoNV, NV1.TenLot, NV1.TenNV, NV2.HoNV, NV2.TenLot, NV2.TenNV 
FROM dbo.NHANVIEN NV1, dbo.DEAN DA, dbo.PHANCONG PC, dbo.NHANVIEN NV2
WHERE DA.MaDA = PC.MaDA AND DA.TenDA = N'Sản phẩm X' AND NV1.MaNV = PC.Ma_NVien AND NV1.PHG = 5 AND NV1.Ma_NQL = NV2.MaNV
AND NV2.HoNV = N'Nguyễn' AND NV2.TenLot = 'Thanh' AND NV2.TenNV = N'Tùng'
-- 10
SELECT NV.HoNV, NV.TenLot, NV.TenNV, DA.TenDA
FROM dbo.NHANVIEN NV, dbo.DEAN DA, dbo.PHANCONG PC
WHERE DA.MaDA = PC.MaDA AND PC.Ma_NVien = NV.MaNV
-- QUERY 3
-- 1
SELECT DA.TenDA, SUM(PC.ThoiGian) AS TONGSOGIOLAMVIEC
FROM dbo.DEAN DA, dbo.PHANCONG PC WHERE DA.MaDA = PC.MaDA
GROUP BY DA.TenDA
-- 2
SELECT NV.HoNV, NV.TenLot, NV.TenNV, COUNT(TN.Ma_NVien) AS SOLUONGTHANNHAN
FROM dbo.NHANVIEN NV, dbo.THANNHAN TN WHERE NV.MaNV = TN.Ma_NVien
GROUP BY NV.HoNV, NV.TenLot, NV.TenNV
-- 3
SELECT PB.TenPHG, AVG(NV.Luong)
FROM dbo.PHONGBAN PB, dbo.NHANVIEN NV WHERE PB.MaPHG = NV.PHG
GROUP BY PB.TenPHG
-- 4
SELECT AVG(NV.Luong)
FROM dbo.NHANVIEN NV WHERE NV.Phai = N'Nữ'
-- 5
SELECT PB.TenPHG, COUNT(NV.MaNV) AS SOLUONGNHANVIEN
FROM dbo.PHONGBAN PB, dbo.NHANVIEN NV WHERE PB.MaPHG = NV.PHG 
GROUP BY PB.TenPHG HAVING AVG(NV.Luong) > 30000
-- 6
SELECT NV.HoNV, NV.TenLot, NV.TenNV, COUNT(PC.Ma_NVien) AS SOLUONGDEAN
FROM PHANCONG PC, dbo.NHANVIEN NV WHERE PC.Ma_NVien = NV.MaNV
GROUP BY NV.HoNV, NV.TenLot, NV.TenNV
-- QUERY 4
-- 1
SELECT PC.MaDA
FROM dbo.NHANVIEN NV, dbo.PHANCONG PC WHERE NV.MaNV = PC.Ma_NVien AND NV.HoNV = N'Đinh'
UNION
SELECT DA.MaDA
FROM dbo.NHANVIEN NV, dbo.PHONGBAN PB, dbo.DEAN DA WHERE NV.MaNV = PB.TrPHG AND PB.MaPHG = DA.Phong AND NV.HoNV = N'Đinh'
-- 2
SELECT NV.HoNV, NV.TenLot, NV.TenNV
FROM dbo.NHANVIEN NV, dbo.THANNHAN TN WHERE NV.MaNV = TN.Ma_NVien 
GROUP BY NV.HoNV, NV.TenLot, NV.TenNV
HAVING COUNT(TN.Ma_NVien) > 2
-- 3
SELECT NV.HoNV, NV.TenLot, NV.TenNV
FROM dbo.NHANVIEN NV, dbo.THANNHAN TN WHERE NV.MaNV = TN.Ma_NVien 
GROUP BY NV.HoNV, NV.TenLot, NV.TenNV
HAVING COUNT(TN.Ma_NVien) = 0
-- 4
SELECT NV.HoNV, NV.TenLot, NV.TenNV
FROM dbo.NHANVIEN NV, dbo.THANNHAN TN, dbo.PHONGBAN PB
WHERE NV.MaNV = TN.Ma_NVien AND NV.MaNV = PB.TrPHG
GROUP BY NV.HoNV, NV.TenLot, NV.TenNV
HAVING COUNT(TN.Ma_NVien) = 0
-- 5
SELECT NV.HoNV, NV.TenLot, NV.TenNV
FROM dbo.NHANVIEN NV 
WHERE NV.Luong > (SELECT AVG(NV1.Luong) FROM dbo.NHANVIEN NV1, dbo.PHONGBAN PB WHERE NV1.PHG = PB.MaPHG AND PB.TenPHG = N'Nghiên cứu')
-- 6
SELECT PB.TenPHG, NV.HoNV, NV.TenLot, NV.TenNV
FROM dbo.NHANVIEN NV, dbo.PHONGBAN PB WHERE NV.MaNV = PB.TrPHG 
AND PB.TenPHG = (SELECT PB.TenPHG FROM dbo.PHONGBAN PB, dbo.NHANVIEN NV WHERE PB.MaPHG = NV.PHG
GROUP BY PB.TenPHG
HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM dbo.PHONGBAN PB, dbo.NHANVIEN NV WHERE PB.MaPHG = NV.PHG GROUP BY PB.TenPHG))
-- 7
SELECT DISTINCT PC.MaDA
FROM dbo.PHANCONG PC, dbo.NHANVIEN NV WHERE NV.MaNV = PC.Ma_NVien 
AND PC.MaDA NOT IN (SELECT PC.MaDA FROM dbo.PHANCONG PC WHERE PC.Ma_NVien = '009')
-- 8
SELECT DISTINCT NV.HoNV, NV.TenLot, NV.TenNV, NV.DChi
FROM dbo.NHANVIEN NV, dbo.PHANCONG PC, dbo.DEAN DA, dbo.DIADIEM_PHG DD 
WHERE NV.MaNV = PC.Ma_NVien AND PC.MaDA = DA.MaDA AND DA.Phong = DD.MaPHG AND DA.Ddiem_DA = 'Tp HCM'
AND DD.DiaDiem NOT IN (SELECT DD.DiaDiem FROM dbo.DIADIEM_PHG DD WHERE DD.DiaDiem = 'Tp HCM')
-- QUERY 5
-- 1
-- NOT EXISTS
SELECT NV.HoNV, NV.TenLot, NV.TenNV
FROM dbo.NHANVIEN NV WHERE NV.MaNV IN (SELECT PC.Ma_NVien FROM dbo.PHANCONG PC
WHERE NOT EXISTS (SELECT * FROM dbo.DEAN DA 
WHERE NOT EXISTS (SELECT * FROM dbo.PHANCONG PC WHERE NV.MaNV = PC.Ma_NVien AND DA.MaDA = PC.MaDA)))
-- EXCEPT
SELECT NV.HoNV, NV.TenLot, NV.TenNV
FROM dbo.NHANVIEN NV WHERE NV.MaNV IN (SELECT PC.Ma_NVien FROM dbo.PHANCONG PC
WHERE NOT EXISTS (SELECT DA.MaDA FROM dbo.DEAN DA
EXCEPT (SELECT PC.MaDA FROM dbo.PHANCONG PC WHERE NV.MaNV = PC.Ma_NVien)))
-- COUNT
SELECT NV.HoNV, NV.TenLot, NV.TenNV
FROM dbo.NHANVIEN NV, dbo.PHANCONG PC, dbo.DEAN DA WHERE NV.MaNV = PC.Ma_NVien AND PC.MaDA = DA.MaDA
GROUP BY NV.HoNV, NV.TenLot, NV.TenNV
HAVING COUNT(PC.MaDA) = (SELECT COUNT(*) FROM DEAN)
-- 2
-- NOT EXISTS
SELECT NV.HoNV, NV.TenLot, NV.TenNV
FROM dbo.NHANVIEN NV WHERE NV.MaNV IN (SELECT PC.Ma_NVien FROM dbo.PHANCONG PC
WHERE NOT EXISTS (SELECT * FROM dbo.DEAN DA WHERE DA.Phong = 4
AND NOT EXISTS (SELECT * FROM dbo.PHANCONG PC WHERE NV.MaNV = PC.Ma_NVien AND DA.MaDA = PC.MaDA)))
-- EXCEPT
SELECT NV.HoNV, NV.TenLot, NV.TenNV
FROM dbo.NHANVIEN NV WHERE NV.MaNV IN (SELECT PC.Ma_NVien FROM dbo.PHANCONG PC
WHERE NOT EXISTS (SELECT DA.MaDA FROM dbo.DEAN DA WHERE DA.Phong = 4
EXCEPT (SELECT PC.MaDA FROM dbo.PHANCONG PC WHERE NV.MaNV = PC.Ma_NVien)))
-- COUNT
SELECT NV.HoNV, NV.TenLot, NV.TenNV
FROM dbo.NHANVIEN NV, dbo.PHANCONG PC, dbo.DEAN DA WHERE NV.MaNV = PC.Ma_NVien AND PC.MaDA = DA.MaDA AND DA.Phong = 4
GROUP BY NV.HoNV, NV.TenLot, NV.TenNV
HAVING COUNT(PC.MaDA) = (SELECT COUNT(*) FROM dbo.DEAN DA WHERE DA.Phong = 4)
-- 3
-- NOT EXISTS
SELECT NV1.HoNV, NV1.TenLot, NV1.TenNV FROM dbo.NHANVIEN NV1 
WHERE NOT EXISTS (SELECT * FROM dbo.DEAN DA, dbo.PHANCONG PC2 WHERE DA.MaDA = PC2.MaDA AND PC2.Ma_NVien = '009'
AND NOT EXISTS (SELECT * FROM dbo.PHANCONG PC2 WHERE PC2.Ma_NVien = NV1.MaNV AND PC2.MaDA = DA.MaDA))
AND NV1.TenNV NOT LIKE N'Tiến'
-- EXCEPT
SELECT NV1.HoNV, NV1.TenLot, NV1.TenNV
FROM dbo.NHANVIEN NV1
WHERE NOT EXISTS (SELECT DA.MaDA FROM dbo.DEAN DA, dbo.PHANCONG PC2 WHERE DA.MaDA = PC2.MaDA AND PC2.Ma_NVien = '009'
EXCEPT (SELECT PC2.MaDA FROM dbo.PHANCONG PC2 WHERE PC2.Ma_NVien = NV1.MaNV))
AND NV1.TenNV NOT LIKE N'Tiến'
-- COUNT
SELECT NV.HoNV, NV.TenLot, NV.TenNV
FROM dbo.NHANVIEN NV, dbo.PHANCONG PC, dbo.DEAN DA WHERE NV.MaNV = PC.Ma_NVien AND DA.MaDA = PC.MaDA
AND PC.MaDA IN (SELECT PC1.MaDA FROM dbo.NHANVIEN NV1, dbo.DEAN DA1, dbo.PHANCONG PC1 WHERE NV1.MaNV = PC1.Ma_NVien AND DA1.MaDA = PC1.MaDA AND NV1.TenNV = N'Tiến')
GROUP BY NV.HoNV, NV.TenLot, NV.TenNV
HAVING COUNT(PC.MaDA) = (SELECT COUNT(*) FROM dbo.PHANCONG PC2, dbo.DEAN DA2, dbo.NHANVIEN NV2 WHERE PC2.MaDA = DA2.MaDA AND PC2.Ma_NVien = NV2.MaNV AND NV2.TenNV = N'Tiến')
AND NV.TenNV NOT LIKE N'Tiến'
-- 4
-- NOT EXISTS
SELECT NV.HoNV, NV.TenLot, NV.TenNV FROM dbo.NHANVIEN NV
WHERE NOT EXISTS (SELECT * FROM dbo.DEAN DA, dbo.CONGVIEC CV, dbo.PHANCONG PC WHERE DA.MaDA = CV.MaDA AND CV.STT = PC.STT AND DA.TenDA = N'Sản phẩm X'
AND NOT EXISTS (SELECT * FROM dbo.PHANCONG PC1 WHERE PC1.Ma_NVien = NV.MaNV AND PC1.MaDA = DA.MaDA AND PC1.STT = CV.STT))
-- EXCEPT
SELECT NV.HoNV, NV.TenLot, NV.TenNV
FROM dbo.NHANVIEN NV
WHERE NOT EXISTS (SELECT DA.MaDA FROM dbo.DEAN DA, dbo.CONGVIEC CV, dbo.PHANCONG PC WHERE DA.MaDA = CV.MaDA AND CV.STT = PC.STT AND DA.TenDA = N'Sản phẩm X'
EXCEPT (SELECT PC1.MaDA FROM dbo.PHANCONG PC1 WHERE PC1.Ma_NVien = NV.MaNV))
-- COUNT
SELECT NV.HoNV, NV.TenLot, NV.TenNV
FROM dbo.NHANVIEN NV, dbo.DEAN DA, dbo.CONGVIEC CV, dbo.PHANCONG PC
WHERE NV.MaNV = PC.Ma_NVien AND PC.MaDA = DA.MaDA AND CV.STT = PC.STT AND DA.MaDA = CV.MaDA AND DA.TenDA = N'Sản phẩm X'
GROUP BY NV.HoNV, NV.TenLot, NV.TenNV
HAVING COUNT(CV.MaDA) = (SELECT COUNT(*) FROM dbo.DEAN DA, dbo.CONGVIEC CV WHERE DA.MaDA = CV.MaDA AND DA.TenDA = N'Sản phẩm X')
ORDER BY NV.HoNV DESC

-- QUERY 2.1
-- 7
SELECT NV.HoNV, NV.TenLot, NV.TenNV
FROM dbo.NHANVIEN NV WHERE YEAR(NV.NgSinh) >= 1960 AND YEAR(NV.NgSinh) <= 1965
-- 8
SELECT NV.HoNV, NV.TenLot, NV.TenNV, YEAR(NV.NgSinh) AS NAMSINH
FROM dbo.NHANVIEN NV
-- 9
SELECT NV.HoNV, NV.TenLot, NV.TenNV, DATEDIFF(YEAR, NV.NgSinh, '2020') AS TUOI
FROM dbo.NHANVIEN NV
-- 18
SELECT DISTINCT DA.TenDA
FROM dbo.PHANCONG PC, dbo.DEAN DA, dbo.NHANVIEN NV WHERE PC.MaDA = DA.MaDA AND NV.MaNV = PC.Ma_NVien AND NV.TenNV = N'Tiến'
-- QUERY 2.2
-- 19
SELECT COUNT(DA.MaDA) AS SOLUONGDEAN
FROM dbo.DEAN DA
-- 20
SELECT COUNT(DA.MaDA) AS SOLUONGDEAN
FROM dbo.DEAN DA, dbo.PHONGBAN PB WHERE DA.Phong = PB.MaPHG AND PB.TenPHG = N'Nghiên cứu'
-- 21
SELECT AVG(NV.Luong)
FROM dbo.NHANVIEN NV WHERE NV.Phai = N'Nữ'
-- 22
SELECT COUNT(TN.Ma_NVien) AS SOTHANNHAN
FROM dbo.THANNHAN TN, dbo.NHANVIEN NV WHERE TN.Ma_NVien = NV.MaNV AND NV.TenNV = N'Tiến'
-- 24
SELECT DA.MaDA, DA.TenDA, COUNT(PC.Ma_NVien) AS SONHANVIENTHAMGIA
FROM dbo.DEAN DA, dbo.PHANCONG PC WHERE DA.MaDA = PC.MaDA 
GROUP BY DA.MaDA, DA.TenDA
-- 25
SELECT NV.HoNV, NV.TenNV, COUNT(TN.Ma_NVien) SOLUONGTHANNHAN
FROM dbo.NHANVIEN NV, dbo.THANNHAN TN WHERE NV.MaNV = TN.Ma_NVien
GROUP BY NV.HoNV, NV.TenNV
-- 26
SELECT NV.HoNV, NV.TenLot, NV.TenNV, COUNT(PC.MaDA) AS SOLUONGDEANTHAMGIA
FROM dbo.NHANVIEN NV, dbo.PHANCONG PC WHERE NV.MaNV = PC.Ma_NVien
GROUP BY NV.HoNV, NV.TenLot, NV.TenNV
-- 27
SELECT NVA.TenNV, COUNT(NVB.MaNV) AS SOLUONGNHANVIENQUANLY
FROM dbo.NHANVIEN NVA, dbo.NHANVIEN NVB WHERE NVA.MaNV = NVB.Ma_NQL
GROUP BY NVA.TenNV
-- 28
SELECT NVA.HoNV, NVA.TenNV, PB.TenPHG
FROM dbo.NHANVIEN NVA, dbo.PHONGBAN PB, dbo.NHANVIEN NVB WHERE NVA.MaNV = NVB.Ma_NQL AND NVA.PHG = PB.MaPHG
GROUP BY NVA.HoNV, NVA.TenNV, PB.TenPHG
HAVING COUNT(NVB.MaNV) >= 2
-- 30
SELECT DD.DiaDiem, COUNT(PB.MaPHG) AS SOLUONGPHONGBAN, COUNT(DA.MaDA) AS SOLUONGDEAN
FROM dbo.PHONGBAN PB, dbo.DEAN DA, dbo.DIADIEM_PHG DD WHERE DD.MaPHG = PB.MaPHG AND DD.DiaDiem = DA.Ddiem_DA
GROUP BY DD.DiaDiem
-- 32
SELECT PB.TenPHG, COUNT(DA.MaDA) AS SOLUONGDEAN
FROM dbo.PHONGBAN PB, dbo.DEAN DA WHERE PB.MaPHG = DA.Phong
GROUP BY PB.TenPHG
-- 33
SELECT PB.TenPHG, NV.HoNV, NV.TenLot, NV.TenNV, COUNT(DA.MaDA) AS SOLUONGDEAN
FROM dbo.PHONGBAN PB, dbo.NHANVIEN NV, dbo.DEAN DA WHERE NV.MaNV = PB.TrPHG AND PB.MaPHG = DA.Phong
GROUP BY PB.TenPHG, NV.HoNV, NV.TenLot, NV.TenNV
-- 36
SELECT DA.TenDA, COUNT(CV.MaDA) AS SOLUONGCONGVIEC
FROM dbo.DEAN DA, dbo.CONGVIEC CV WHERE DA.MaDA = CV.MaDA
GROUP BY DA.TenDA
-- 37
SELECT COUNT(PC.Ma_NVien) AS SOLUONGNHANVIENPHANCONG
FROM dbo.CONGVIEC CV, dbo.PHANCONG PC WHERE CV.MaDA = PC.MaDA AND CV.STT = PC.STT AND PC.MaDA = 30
-- 38
SELECT COUNT(PC.Ma_NVien) AS SOLUONGNHANVIENPHANCONG
FROM dbo.DEAN DA, dbo.CONGVIEC CV, dbo.PHANCONG PC WHERE DA.MaDA = CV.MaDA AND CV.STT = PC.STT AND CV.MaDA = PC.MaDA AND DA.TenDA = N'Đào tạo'
-- QUERY 2.3
-- 42
SELECT NV.HoNV, NV.TenLot, NV.TenNV
FROM dbo.NHANVIEN NV, dbo.THANNHAN TN WHERE NV.MaNV = TN.Ma_NVien
GROUP BY NV.HoNV, NV.TenLot, NV.TenNV
HAVING COUNT(TN.Ma_NVien) >= ALL (SELECT COUNT(TN.Ma_NVien) FROM dbo.NHANVIEN NV, dbo.THANNHAN TN WHERE NV.MaNV = TN.Ma_NVien GROUP BY TN.Ma_NVien)
-- 43
SELECT DD.DiaDiem
FROM dbo.DIADIEM_PHG DD, dbo.PHONGBAN PB WHERE DD.MaPHG = PB.MaPHG 
GROUP BY DD.DiaDiem
HAVING COUNT(DD.MaPHG) >= ALL (SELECT COUNT(DD.MaPHG) FROM dbo.DIADIEM_PHG DD, dbo.PHONGBAN PB WHERE DD.MaPHG = PB.MaPHG GROUP BY DD.DiaDiem)
-- 44
SELECT NV.HoNV, NV.TenLot, NV.TenNV
FROM dbo.NHANVIEN NV, dbo.THANNHAN TN, dbo.PHONGBAN PB WHERE NV.MaNV = TN.Ma_NVien AND NV.MaNV = PB.TrPHG
GROUP BY NV.HoNV, NV.TenLot, NV.TenNV
HAVING COUNT(TN.Ma_NVien) >= 1
-- 45
SELECT NV.HoNV, NV.TenNV
FROM dbo.NHANVIEN NV WHERE NOT EXISTS (SELECT * FROM dbo.THANNHAN TN, dbo.PHONGBAN PB WHERE TN.Ma_NVien = NV.MaNV AND PB.TrPHG = NV.MaNV)
-- 46
SELECT NV.HoNV, NV.TenLot, NV.TenNV
FROM dbo.NHANVIEN NV WHERE NV.Luong >= (SELECT AVG(NV.Luong) FROM dbo.NHANVIEN NV, dbo.PHONGBAN PB WHERE PB.MaPHG = NV.PHG AND PB.TenPHG = N'Nghiên cứu') 
-- 47
SELECT NV.HoNV, NV.TenLot, NV.TenNV
FROM dbo.NHANVIEN NV 
WHERE NV.Luong >= ALL (SELECT NV.Luong FROM dbo.NHANVIEN NV)
-- 48
SELECT NV.PHG, MAX(NV.Luong) AS LUONGLONNHAT
FROM dbo.NHANVIEN NV
GROUP BY NV.PHG
-- 49
SELECT NV.HoNV, NV.TenLot, NV.TenNV
FROM dbo.NHANVIEN NV, dbo.DEAN DA1, dbo.DEAN DA2, dbo.PHANCONG PC1, dbo.PHANCONG PC2
WHERE NV.MaNV = PC1.Ma_NVien AND NV.MaNV = PC2.Ma_NVien AND PC1.MaDA = DA1.MaDA AND PC2.MaDA = DA2.MaDA AND DA1.TenDA = N'Đào tạo' AND DA2.TenDA = N'Sản phẩm X'
-- 50
SELECT PB.TenPHG, COUNT(NV.MaNV) AS SOLUONGNHANVIEN
FROM dbo.NHANVIEN NV, dbo.PHONGBAN PB WHERE NV.PHG = PB.MaPHG
GROUP BY PB.TenPHG
HAVING COUNT(NV.MaNV) >= ALL (SELECT COUNT(NV.MaNV) FROM dbo.NHANVIEN NV GROUP BY NV.PHG)
-- QUERY 2.4
-- 59
-- NOT EXISTS
SELECT NV.HoNV, NV.TenLot, NV.TenNV
FROM dbo.NHANVIEN NV WHERE NV.MaNV IN (SELECT PC.Ma_NVien FROM dbo.PHANCONG PC
WHERE NOT EXISTS (SELECT * FROM dbo.DEAN DA WHERE DA.Ddiem_DA = N'TP HCM'
AND NOT EXISTS (SELECT * FROM dbo.PHANCONG PC WHERE NV.MaNV = PC.Ma_NVien AND DA.MaDA = PC.MaDA)))
-- EXCEPT
SELECT NV.HoNV, NV.TenLot, NV.TenNV
FROM dbo.NHANVIEN NV WHERE NV.MaNV IN (SELECT PC.Ma_NVien FROM dbo.PHANCONG PC
WHERE NOT EXISTS (SELECT DA.MaDA FROM dbo.DEAN DA WHERE DA.Ddiem_DA = N'TP HCM'
EXCEPT (SELECT PC.MaDA FROM dbo.PHANCONG PC WHERE NV.MaNV = PC.Ma_NVien)))
-- COUNT
SELECT NV.HoNV, NV.TenLot, NV.TenNV
FROM dbo.NHANVIEN NV, dbo.PHANCONG PC, dbo.DEAN DA WHERE NV.MaNV = PC.Ma_NVien AND PC.MaDA = DA.MaDA AND DA.Ddiem_DA = N'TP HCM'
GROUP BY NV.HoNV, NV.TenLot, NV.TenNV
HAVING COUNT(PC.MaDA) = (SELECT COUNT(*) FROM DEAN DA WHERE DA.Ddiem_DA = N'Hà Nội' GROUP BY DA.Ddiem_DA)
-- 60
-- NOT EXISTS
SELECT PB.TenPHG
FROM dbo.PHONGBAN PB 
WHERE NOT EXISTS (SELECT * FROM dbo.DEAN DA WHERE DA.Ddiem_DA = N'TP HCM'
AND NOT EXISTS (SELECT * FROM dbo.PHONGBAN PB1 WHERE PB1.MaPHG = DA.Phong AND PB1.MaPHG = PB.MaPHG))
-- EXCEPT
SELECT PB.TenPHG
FROM dbo.PHONGBAN PB 
WHERE NOT EXISTS (SELECT DA.Phong FROM dbo.DEAN DA WHERE DA.Ddiem_DA = N'TP HCM'
EXCEPT (SELECT PB1.MaPHG FROM dbo.PHONGBAN PB1 WHERE PB1.MaPHG = PB.MaPHG))
-- COUNT
SELECT PB.TenPHG
FROM dbo.PHONGBAN PB, dbo.DEAN DA, dbo.PHONGBAN PB1 WHERE PB.MaPHG = DA.Phong AND DA.Phong = PB1.MaPHG AND DA.Ddiem_DA = N'TP HCM'
GROUP BY PB.TenPHG
HAVING COUNT(PB1.MaPHG) = (SELECT COUNT(*) FROM dbo.DEAN DA WHERE DA.Ddiem_DA = N'TP HCM' GROUP BY DA.Ddiem_DA)